### ISSUE TITLE
Filter: account list

### ISSUE THREAD

**Issue by cuteolaf** [TaoStats/bittensor-explorer-ui#114]
Filter the account list based on the amount of total balance > +100k, +50k, +10k, +5k, +1k , ...

**Comment by TopETH** [comment]
@mog Do you have any idea about filtering accounts?
Where should I place filter option in the table?

**Comment by mogmachine** [comment]
I am surprised by the question ..filters usually always go above a table with search: https://grab.mogmachine.com/DOuPGoJd  ..you just need to look at taostats and you will see the search, filters etc.

All our tables are also missing page numbers ...you can go to next and previous ..but you can't go to last, or a specific. 

I would LOVE the pagination to look and work EXACTLY the same as TaoStats ...is this possible under the same task

- 'show' top left
- 'search' top right
- 'pagination with numbers' bottom right
- 'current position and total rows' bottom left
- 'additional filters' top (if space in one row) or collapsable top row under 'show' called 'filter'
