### ISSUE TITLE
Different background color of loading gif from card background

### ISSUE THREAD

**Issue by TopETH** [TaoStats/bittensor-explorer-ui#118]
![image](https://github.com/TaoStats/bittensor-explorer-ui/assets/79193919/68eb5c19-9fca-4630-8726-b94b5bff1126)

The background color of the loading GIF is #191919, while the main background color of the card is #1a1a1a. This dissonance in colors results in a poor design for the loading component. Therefore, I recommend harmonizing the background colors of either the loading GIF or the card to create a more cohesive and visually pleasing design.

**Comment by TopETH** [comment]
I propose a straightforward solution to enhance our project. By updating the primary dark color to #191919, we can achieve a more desirable outcome.

**Comment by mogmachine** [comment]
Ha ... the loader is not the right background colour so change all the background colours on the site! No. 

Change the loader background colour of course! It is a simple loader generated from one of those preloader generator sites.
![Spinner-1s-201px](https://github.com/TaoStats/bittensor-explorer-ui/assets/3446536/b81e8794-afda-4a14-8c75-14319da68ca9)
![Spinner-1s-201px](https://github.com/TaoStats/bittensor-explorer-ui/assets/3446536/cad7b97d-ce6c-45d3-9fa5-5bcb154829f3)

There you go.

**Comment by mogmachine** [comment]
We can replace all spinners with this nice lighter weight more unique one.
GIF and SVG versions. Max width 200px. Never larger.
