### ISSUE TITLE
Project Analysis

### ISSUE THREAD

**Issue by cute0laf** [TaoStats/bittensor-explorer-ui#3]
- [x] What is the styling framework used?
- [x] How are the components structured?
- [x] How's the search implemented?
- [x] How's the pagination implemented?
- [x] How are the GraphQL queries structured and processed?
- [x] Hooks

**Comment by TopETH** [comment]
What is the styling framework used?
Material UI is used for styling framework.

**Comment by TopETH** [comment]
How's the pagination implemented?

The GraphQL response has pagination data.
And it is sent to -> ItemsTable -> TablePagination as props and pagination is implemented there.

![pagination](https://github.com/TaoStats/bittensor-explorer-ui/assets/79193919/33c6edca-d98a-4eaa-b44f-83fe7b41fae2)

**Comment by TopETH** [comment]
How's the search implemented?

Analyze the query first whether it is
1. extrinsic hash or block hash
2. account address
3. block height
4. extrinsic name or event name
