### ISSUE TITLE
Page: Account Details

### ISSUE THREAD

**Issue by cute0laf** [TaoStats/bittensor-explorer-ui#4]
- [x] Remove tab: `Balances`
As we only need to show the TAO balance of an account, we can remove the tab.
- [x] Update the portfolio chart
  - [x] Change "Portfolio" into "Account Balance"
  - [x] Remove chart (`By network`)
- [x] Remove tab: `Calls`

**Comment by cuteolaf** [comment]
Originally, I was thinking of using with the GraphQL endpoint to fetch account balance. But making a such entity is not efficient enough.
For now, let's make an API call in the front-end to fetch user balance.
