### ISSUE TITLE
Delegation breakdown on account page

### ISSUE THREAD

**Issue by mogmachine** [TaoStats/bittensor-explorer-ui#65]
Under total balance in the left section it should show

Delegated Balance: 23,500 TAO (Opentensor Foundation) \n 13,500 TAO (TaoStats)

each on a new line.

Basically the same information you get here: https://taostats.io/delegate/?key=5Fc7nn2sDGKm9QS26e94NG7reVcG4s1zKEVMRJBwKb7RReGT and then of course we can incorporate that chart.

![image](https://github.com/TaoStats/bittensor-explorer-ui/assets/79193919/2f0b0d54-450f-490a-8d62-91840b143d0a)

**Comment by cute0laf** [comment]
https://github.com/TaoStats/bittensor-indexer/issues/32

**Comment by mogmachine** [comment]
@TopETH issues as follows:

BUG:
- many top wallets are not showing anything even though they are delegated: https://bittensor-explorer-ui-git-topeth-delegate-breakdown-tao-stats.vercel.app/account/5CfvfoLvkpRuJ77zpgmE7ooPWEHVWvyZvBxV9ncDuCmwLWEd

FORMATTING
- we need name/address and amount consistently spaced. Name/Address first then amount on new line
- No  ()'s needed for name

>> like this: https://grab.mogmachine.com/P8uDZm6L

**Comment by mogmachine** [comment]
@TopETH  ...do you think you have enough data to implement the chart?
