### ISSUE TITLE
Block Details

### ISSUE THREAD

**Issue by TopETH** [TaoStats/bittensor-explorer-ui#75]
Number of events, extrinsics

**Comment by TopETH** [comment]
This requires update of the backend, doesn't it? @cute0laf

**Comment by TopETH** [comment]
Once the dictionary project is updated, we can add new columns(number of extrinsics, events) to the blocks table and do ordering by number of extrinsics/events.

**Comment by cute0laf** [comment]
https://github.com/TaoStats/bittensor-dictionary/issues/24

**Comment by cute0laf** [comment]
https://github.com/TaoStats/bittensor-explorer-ui/issues/100
